name: API Dependency Update
on:
  push:
    branches:
      - master
jobs:
  Update-Api-Dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: actions/checkout@master
        with:
          repository: RevolutionUC/revolutionuc-api
          token: ${{ secrets.PAT }}
          
          

      - run: yarn install
      - run: yarn upgrade revolutionuc-emails

      - uses: EndBug/add-and-commit@v9
        with:
          add: "yarn.lock"
          default_author: user_info
          message: "emails package auto update"
          push: true
