name: API Dependency Update
on:
  push:
    branches:
      - master
jobs:
  Update-Api-Dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - uses: actions/checkout@master
        with:
          repository: RevolutionUC/revolutionuc-api
          token: ${{ secrets.PAT_ORG }}
          
          

      - run: npm install
      - run: npm update revolutionuc-emails

      - uses: EndBug/add-and-commit@v8
        with:
          add: "package-lock.json"
          default_author: user_info
          message: "emails package auto update"
          push: true
