name: GitHub Actions Demo
on: [push]
jobs:
  Update-Api-Dep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/checkout@master
        with:
          repository: RevolutionUC/revolutionuc-api
      - run: npm install
      - run: npm update revolutionuc-emails
      - run: git push
